### ISSUE TITLE
Multiple browser support

### ISSUE THREAD

**Issue by jcaffera42** [Ni55aN/D3-Node-Editor#22]
I've found that the library is not working properly on Edge and Firefox. The nodes are cropped (but functional), and in Edge the dragging is odd.
Is there any chance of making it work fully in Edge and Firefox?

Thanks!

**Comment by Ni55aN** [comment]
@jcaffera42, I solve the problem with Firefox now.  I'll try to solve the problem with Edge later

**Comment by Ni55aN** [comment]
Nodes moved from svg to html, now there should be no problems.
Please check in the Edge how it will behave

**Comment by jcaffera42** [comment]
Thanks! That was really fast! Working perfectly on Edge, however, in firefox I can't add nodes using the context menu anymore.

**Comment by Ni55aN** [comment]
@jcaffera42, it was my mistake before the release. This is fixed in the following commits. 
You can collect for yourself from the sources or get files by links
https://d3-node-editor.surge.sh/node-editor.js
https://d3-node-editor.surge.sh/node-editor.css
https://d3-node-editor.surge.sh/menu.html
https://d3-node-editor.surge.sh/view.html

**Comment by jcaffera42** [comment]
It still has issues on Edge. The connections look misplaced, and you can drag the nodes out of the container. (On Chrome and Firefox it's working properly)

**Comment by Ni55aN** [comment]
Can you place your example with all styles?

Are there any problems in the [demo](https://codepen.io/Ni55aN/pen/jBEKBQ)?
On my Edge 38 everything looks good

**Comment by jcaffera42** [comment]
You're right, the demo works perfectly. I'll check my code again to find the issue, thanks!
