### ISSUE TITLE
Get component by name

### ISSUE THREAD

**Issue by jcaffera42** [Ni55aN/D3-Node-Editor#28]
When getting the builders of the components, in the demo you get them by position, like this:

`var menu = new D3NE.ContextMenu({
                'Actions':{
                    'Action': function(){alert('Subitem selected');}
                },
                'Nodes':{
                    'Number': components[0].builder, 
                    'Add': components[1].builder
                }
           });`

In my opinion it would be much more useful to get the builders by their name, something like `components.getComponent('number').builder,` mainly because if the components are loaded dynamically, you probably won't know the order in which they are added into the collection (this is my case).

Thanks!

**Comment by Ni55aN** [comment]
You can implement [a similar object](https://github.com/Ni55aN/allmatter/blob/master/src/editor/components/index.js#L27) (then [getting builders](https://github.com/Ni55aN/allmatter/blob/master/src/components/NodeEditor.vue#L51) will be more convenient)
Since the NodeEditor and Engine only need arrays with components, you can create any wrappers for them for your convenience.
