### ISSUE TITLE
Best way to do socket verification?

### ISSUE THREAD

**Issue by janhaa** [Ni55aN/d3-node-editor#34]
For example I have created a [ObjectId](https://docs.mongodb.com/manual/reference/method/ObjectId/) socket which should only allow values of /^[a-fA-F0-9]{24}$/.

I mean I could verify it at every worker, but that seems burdensome...

Any hints?

PS: Great work on this thing btw!

**Comment by Ni55aN** [comment]
A socket should know nothing about the data that passes through it. It only controls that user can not connect incompatible sockets.

It's impossible to pass something to the input with the ObjectId socket from the output with another socket (of course until you allow it with `.combineWith`)

All data control takes place in workers, and only you control what to send to output.

**Comment by janhaa** [comment]
But since you can define different sockets, I think data verification could have its place there.

I mean, at the moment this implicates I could pass strings through a socket defined as a "number".

**Comment by Ni55aN** [comment]
> I mean, at the moment this implicates I could pass strings through a socket defined as a "number".

it's possible to do it in a worker, but not when working through the GUI itself. When you know, for example, that the second output has a "number" socket, then you do something like the following:
```js
worker(node, inputs, outputs){
   outputs[1] = /*number*/
}
```
you just do not need to send something else

**Comment by janhaa** [comment]
I don't see the reason for having different sockets when the only thing it does is verifying connections - verifying passing data would be perfect in that context from my point of view :-)

**Comment by Ni55aN** [comment]
If there were no sockets, then it was possible to connect the output String with a input Number, which would not be correct. And then, yes, it would be necessary to verify the data. 
But with socket compatibility checking, there is no need to check the data, because they simply can not get to the input

**Comment by janhaa** [comment]
"because they simply can not get to the input" what do you mean?

**Comment by Ni55aN** [comment]
I mean that only data from a compatible socket can be passed to the input, so there is no need to check them.

![2017-12-14_223307](https://user-images.githubusercontent.com/8259641/34013149-049e0c62-e11f-11e7-942a-8e0cff77547a.png)
As you can see, to calculate the sum of two numbers it is impossible to pass a string, since the sockets are incompatible

**Comment by floric** [comment]
I just pick up this ticket, I would like to add my 2 cents to this discussion:

I'm currently planning an interactive tool for data and visual analytics. You can pass in datasets, select columns and combine/aggregate these datasets with certain operators.

I also see the need to have a validation callback for input sockets as for example the datatype could be dynamic (eg. certain columns in the created datasets need to be present) and not only rely on the the socket type. Another point would be for example to dynamically define the available options of controls based on the current input. This would require a callback for connection changes and the ability to change controls based on these changes.

If you like, I'd be happy to take a look at the code and give it a try. But maybe it's not possible with the current architecture?!

**Comment by Ni55aN** [comment]
>  datatype could be dynamic

Yeah, that's why the editor does not have to interact with the data (it only stores them), since it does the Engine in isolation. 
All the checks with the data you can do in the workers, where if necessary interact with the editor.

> If you like, I'd be happy to take a look at the code and give it a try. But maybe it's not possible with the current architecture?!

I hope I can find a solution with the current architecture, if you provide an example of your editor

**Comment by floric** [comment]
Thanks: I'm currently doing some tests and validating my possibilities. I think my planned usecase is greater and little different to what D3ne currently offers. So I need to build some new code anyway around it.

**Comment by floric** [comment]
Hey @Ni55aN :)
Feel free to close this ticket again. I decided to develop my own node editor as I will require a few more features as well as flexibility. If you like, I can share my results or progress with you. It's currently part of my project but could be separated into a separate package later. It's currently based on konva.

**Comment by janhaa** [comment]
@floric Hi Florian! Has there been progress on your own node editor ? If so I would like to take a look as I am currently again looking for one, please hit me up: jan.haeusler@rwth-aachen.de
