### ISSUE TITLE
Cannot use an id below 100

### ISSUE THREAD

**Issue by Thomas-Negrault** [Ni55aN/d3-node-editor#39]
The regex of the `isValidId` function:`/^[\w-]{3,}@[0-9]+\.[0-9]+\.[0-9]+$/
`is too restrictive. When I create a new "document" I would like its id to be 0 but unfortunately we **need** to have at least 3 chars for the id part. I cannot use the fromJson without having the error:

> Uncaught Error: ID should be valid to name@0.1.0 format

We also **need** to provide a version number (and an int is not ok, we need to use x.y.z)
I am not working with versioning right now so I am juste adding @0.0.1 to the end of my id. 
Is there any way to bypass theses errors ? 

The id regex could be a minimum of 1 char instead of 3, why not use 1,2,3...10 as id instead of beginning at 100 ?
And the version parameter could be optional as well

**Comment by Ni55aN** [comment]
ID has that format for several reasons:
- Name determines the purpose of data 
Most likely it will be the name of your application. The name "1" is not informative and it is not clear to which application this data is applied (especially if they are stored in a file)

- Check data integrity according to the version
  Your editor may be improved. An old data may remain (as a file on the user's disk, in a database or somewhere else), and attempts to use them in a new editor may be unpredictable. Therefore, you need to know the version in the form of x.y.z to understand whether it is possible somehow to combine the old data with the new editor.
For example, you have the data with version 0.1.0. You changed something insignificant in your editor and gave it version 0.1.1. Most likely, the old data can be slightly changed so that they can be imported into the editor without problems.
And if you changed the editor a lot, then most likely he needs to give version 0.2.0 and specify in such a way that it will be possible to combine old data, but it is problematic.
