### ISSUE TITLE
[Angular] Draggable problems

### ISSUE THREAD

**Issue by Lemonify** [Ni55aN/d3-node-editor#43]
Hello,

I tried to implement node editor in Angular 5 as it is provided in example and wiki. However, the drag functionality seems to be malfunctioning - if I click on a component, it somehow triggers the canvas (div) drag event and it is impossible to move the components or connect them.

Is this something on my side or it might be a problem with outdated example/wiki article?

**Comment by Ni55aN** [comment]
Yeah, I have noticed this problem in the example with Angular 4. Seems like Angular override pure events handlers. 
Earlier I was not able to solve this problem, since the problem is probably not on the side of the library. In other environments such a problem is not observed.
So, I'll try to found the reason of problem

**Comment by Ni55aN** [comment]
The problem disappeared after updating angular-cli to v1.7.4
https://github.com/Ni55aN/D3NE-examples/commit/5a7071052a2e8321c97d8a3ab1394643e685cf47
