### ISSUE TITLE
is it possible to modify node from worker?

### ISSUE THREAD

**Issue by GeorgiyZhuravlev** [Ni55aN/d3-node-editor#47]
Hi!
First of all `d3-node-editor` is awesome! I've spent some time to find a tool like this. I'm trying to use it to draw/describe testing scenarios for our app (hypermedia siren api). I looked at `node-red` as a possible candidate but it's too heavy and not very easy to use for non-developers. And your library looks like a perfect fit for our use case. Thanks!

Small question: 
I looked at "Customisation" page in wiki but if I'm fine with the built-in template is it possible to update node data used in the template through the worker? I was trying to do something like this:
```
 // doesn't work for me
 async worker(node, inputs, outputs) {
    await something();
    node.title += ' - done!';
 }

 // somewhere later, on "start" button click
 await engine.process(editor.toJSON());
 // doesn't help either
 editor.view.update();
```

If the whole approach is bad - please point me in the right direction.

**Comment by Ni55aN** [comment]
Hi @GeorgiyZhuravlev Thanks, I'm glad you like it!

`node` argument in `worker` is equal to yourNode.toJSON(), not instance itself. That data come from `editor.toJSON()`. This is necessary in order to perform the processing of nodes regardless of the editor

So, to get a node instance in the editor, you need to find it according to id from `editor.nodes `. 
```
editor.nodes.find(n => n.id == node.id)
````
But you shouldn't change a title of node instance (the title is a sort of node type identifier).
For your task, this solution may be appropriate: https://jsfiddle.net/Ni55aN/8pfqb9yy/22/. Just used custom template with data._done checking. (I think that property should be indicated with an underscore because it is not permanent (for example, they are not important to us when exporting editor's data)

**Comment by GeorgiyZhuravlev** [comment]
Thanks!
