### ISSUE TITLE
Message on the console log after updating from 0.6.0 to 0.6.10

### ISSUE THREAD

**Issue by Hamdiovish** [Ni55aN/d3-node-editor#67]
Hello guys,
Thanks for the great work and the continious updates,
When i updated the lib from 0.6.0 to 0.6.10, i started seeing this message in the console log:
"The process is busy and has not been restarted. Use abort() to force it to complete
processStart" @ engine.js:67

**Comment by Ni55aN** [comment]
How do you call the `engine.process()`?

If you have asynchronous workers and processing can be called very often, then preferable is:
```
editor.eventListener.on('change', async () => {
    await engine.abort();
    await engine.process(editor.toJSON());   
});
```

The `engine.process` can be called at a time when the previous processing was not completed. Therefore, it is better to abort the previous processing with `engine.abort();` since the instance is one and it can not simultaneously do several processing.

https://github.com/Ni55aN/d3-node-editor/wiki/Engine#processing

**Comment by Hamdiovish** [comment]
Clear!
Thanks man
