### ISSUE TITLE
Customization of auxilaries points

### ISSUE THREAD

**Issue by ALPEEN** [Ni55aN/d3-node-editor#92]
UX Suggestion:
![2017_10_28_12_43_35](https://user-images.githubusercontent.com/38503508/39662687-aa41a2c0-505d-11e8-94a9-4b2d1ef93f9e.png)

Provide the ability to the user to add as much auxilaries points as he want, with the ability to move them freely via drag and drop.
Such feature can give the user the ability to organize big and complexe workspaces and remove paths-congestion from the graph.

**Comment by trsh** [comment]
Not critical in my project, but can imagine when the nodes get A LOT, this being useful.

**Comment by Ni55aN** [comment]
And this is again an extra complexity. If the number of nodes is too large, then it makes sense to divide them into modules.

**Comment by trsh** [comment]
@Ni55aN you convinced me this a not so great idea after all. Let's make this a vote?

**Comment by Ni55aN** [comment]
@trsh I'm not against adding such features, but not directly to the library codebase.
Most of all I don't want the library to grow functional, which will be difficult to maintain.
That's why I'm currently researching possible interfaces that will be needed for plugins, and I'm going to implement plugin support.

**Comment by trsh** [comment]
@Ni55aN clear, then let's just close this ;)
