### ISSUE TITLE
[question] process busy

### ISSUE THREAD

**Issue by trsh** [Ni55aN/d3-node-editor#95]
```
The process is busy and has not been restarted.
                Use abort() to force it to complete

```
I got these warnings, when connecting to input that is already set (replace case). What's the proper way to handle it?

**Comment by Ni55aN** [comment]
just call `await angine.abort()` before `process()`

**Comment by trsh** [comment]
@Ni55aN 
Ok, pleas open https://codepen.io/Ni55aN/pen/jBEKBQ. Then just take one output Of number node, and place it in same socket it's already. The warn appears. Neverless the abort is set:

```
editor.eventListener.on("change", async function() {
   await engine.abort();
   await engine.process(editor.toJSON());
});
```

So it'' a bug?

**Comment by Ni55aN** [comment]
Not really, it's the specifics of calling asynchronous functions. And the following is obtained:
from the same stack, the "change" event is called twice and the call has the following form:
```js
trigger ("change") // sync
trigger ("change") // sync
```
As a result, functions are called in the following sequence, since abort is asynchronous
```js
abort ();
abort ();
process ();
process ();
```
but not like this
```js
abort ();
process ();
abort ();
process ()
```
In this form, the call order will be correct.

```js
requestAnimationFrame (async () => {
   await engine.abort ();
   await engine.process (editor.toJSON (), 1);
});
```
Perhaps someone knows the more correct way to call a chain of asynchronous functions in sequence

**Comment by trsh** [comment]
This big junk solves the issue :D, but it's tooooo BIG

```
var inProgress = null;

editor.eventListener.on("change", async() => {
   console.log(inProgress);
   if(inProgress){
      inProgress.then(() => {
         editor.eventListener.trigger('change');
      });
   }else{
      inProgress = new Promise(async(resolve, reject) => {
         await engine.abort ();
         await engine.process (editor.toJSON ());
         resolve();
         inProgress = null;
      });   
   }
});
```
